name: MigTool continuous build
# read more here
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - '**'
      - '!refs/tags/.*'
    tags-ignore:
      - '**'

jobs:
  build-linux:
    name: Migtool build for linux-x86
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Tests
        run: ./gradlew check

      - name: Tests reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: linux-test-reports
          path: build/reports/tests/test/
          overwrite: true

      - name: Build Native Image
        run: ./gradlew nativeCompile

      - name: Upload linux native image artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: migtool-linux-x86
          path: build/native/nativeCompile/migtool
          overwrite: true

      - name: Tests native
        run: ./gradlew cleanTest check
        env:
          NATIVE_BINARY_PATH: build/native/nativeCompile/migtool

      - name: TestsNative reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: linux-testsNative-reports
          path: build/reports/tests/nativeCliTest/
          overwrite: true

  build-macos:
    name: Migtool build for MacOS-arm64
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build Native Image
        run: ./gradlew nativeCompile

      - name: Codesign binary
        if: contains(github.event.head_commit.message, '[release]') && github.event.ref == 'refs/heads/master'
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime build/native/nativeCompile/migtool -v

      - name: Notarize binary
        if: contains(github.event.head_commit.message, '[release]') && github.event.ref == 'refs/heads/master'
        env:
          MACOS_AC_API_CERT: ${{ secrets.MACOS_AC_API_CERT }}
          MACOS_AC_API_ISSUER_ID: ${{ secrets.MACOS_AC_API_ISSUER_ID }}
          MACOS_AC_API_KEY_ID: ${{ secrets.MACOS_AC_API_KEY_ID }}
        run: |
          echo $MACOS_AC_API_CERT | base64 --decode > AuthKey.p8
          xcrun notarytool store-credentials "notarytool-profile" -k AuthKey.p8 -d "$MACOS_AC_API_KEY_ID" -i "$MACOS_AC_API_ISSUER_ID"
          ditto -c -k --keepParent "build/native/nativeCompile/migtool" "notarization.zip"
          xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait

      - name: Upload MacOS native image artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: migtool-macos-arm64
          path: build/native/nativeCompile/migtool
          overwrite: true

  release:
    name: Release
    if: "contains(github.event.head_commit.message, '[release]') && github.event.ref=='refs/heads/master'"
    needs: [ build-linux, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - name: Setup Java for JReleaser
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Version
        id: version
        run: |
          VERSION=$(cat ./VERSION)
          echo "VERSION = $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ steps.version.outputs.VERSION }}
